=== jpromocion/plsql-j-utilxml/pldoc/application.dtd
<!ELEMENT APPLICATION ( OVERVIEW?, (OBJECT_TYPE |PACKAGE | TABLE | TRIGGER| PACKAGE_BODY | OBJECT_BODY)*, SUMMARY?, GENERATOR? ) >
<!ATTLIST APPLICATION NAME CDATA #REQUIRED >

<!ELEMENT ARGUMENT ( COMMENT? ) >
<!ATTLIST ARGUMENT NAME CDATA #REQUIRED >
<!ATTLIST ARGUMENT TYPE CDATA #REQUIRED >
<!ATTLIST ARGUMENT DEFAULT CDATA #IMPLIED >
<!ATTLIST ARGUMENT MODE CDATA #IMPLIED >

<!ELEMENT COMMENT ( #PCDATA ) >

<!ELEMENT COMMENT_FIRST_LINE ( #PCDATA ) >

<!ELEMENT CONSTANT ( COMMENT | COMMENT_FIRST_LINE | RETURN  )* >
<!ATTLIST CONSTANT DEFAULT CDATA #IMPLIED >
<!ATTLIST CONSTANT NAME CDATA #REQUIRED >

<!ELEMENT CURSOR ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | RETURN )* >
<!ATTLIST CURSOR NAME CDATA #REQUIRED >

<!ELEMENT TAG ( COMMENT? ) >
<!ATTLIST TAG TYPE CDATA #REQUIRED >
<!ATTLIST TAG NAME CDATA #IMPLIED >

<!ELEMENT EXCEPTION ( ( COMMENT | COMMENT_FIRST_LINE )*  )* >
<!ATTLIST EXCEPTION NAME CDATA #REQUIRED >

<!ELEMENT FUNCTION ( ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | RETURN | TAG | THROWS )* , SUMMARY? ) >
<!ATTLIST FUNCTION NAME CDATA #REQUIRED >
<!ATTLIST FUNCTION ACTION CDATA #IMPLIED >
<!ATTLIST FUNCTION VERSION CDATA #IMPLIED >
<!ATTLIST FUNCTION INHERITANCE CDATA #IMPLIED >
<!ATTLIST FUNCTION ORDERING CDATA #IMPLIED >
<!ATTLIST FUNCTION SCOPE CDATA #IMPLIED >

<!ELEMENT OVERVIEW ( #PCDATA ) >

<!-- 20110418 SRT Allow Object Types to be specified as Object Types-->
<!ELEMENT OBJECT_TYPE ( ( COMMENT | CONSTANT | FUNCTION | PROCEDURE | VARIABLE | COLLECTIONTYPE | SUPERTYPE | TAG | PRAGMA )* , SUMMARY? ) >
<!ATTLIST OBJECT_TYPE NAME CDATA #REQUIRED >
<!ATTLIST OBJECT_TYPE SCHEMA CDATA #IMPLIED >

<!ELEMENT PRAGMA ( #PCDATA ) >
<!ATTLIST PRAGMA NAME CDATA #REQUIRED >

<!ELEMENT OBJECT_BODY ( ( COMMENT | CONSTANT | FUNCTION | PROCEDURE | VARIABLE | COLLECTIONTYPE | SUPERTYPE | TAG )* , SUMMARY? ) >
<!ATTLIST OBJECT_BODY NAME CDATA #REQUIRED >
<!ATTLIST OBJECT_BODY SCHEMA CDATA #IMPLIED >

<!ELEMENT PACKAGE_BODY ( ( COMMENT | CONSTANT | CURSOR | EXCEPTION | FUNCTION | PROCEDURE | TYPE | VARIABLE | TAG )* , SUMMARY? ) >
<!ATTLIST PACKAGE_BODY NAME CDATA #REQUIRED >
<!ATTLIST PACKAGE_BODY SCHEMA CDATA #IMPLIED >


<!ELEMENT SUPERTYPE ( COMMENT | COMMENT_FIRST_LINE | RETURN )* >
<!ATTLIST SUPERTYPE NAME CDATA #REQUIRED >

<!ELEMENT COLLECTIONTYPE ( COMMENT | COMMENT_FIRST_LINE )* >
<!ATTLIST COLLECTIONTYPE NAME CDATA #REQUIRED >

<!-- 20110418 SRT Allow Object Types to be specified as Object Types-->

<!ELEMENT PACKAGE ( ( COMMENT | CONSTANT | CURSOR | EXCEPTION | FUNCTION | PROCEDURE | TYPE | VARIABLE | TAG | TRIGGER | PRAGMA )* , SUMMARY? ) >
<!ATTLIST PACKAGE NAME CDATA #REQUIRED >
<!ATTLIST PACKAGE SCHEMA CDATA #IMPLIED >

<!--  20110419 TEMPORARILY  allow PROCEDURE to  RETURN  - until parser populates 
<!ATTLIST PROCEDURE INHERITANCE CDATA #IMPLIED >
<!ATTLIST PROCEDURE ORDERING CDATA #IMPLIED >
<!ATTLIST PROCEDURE SCOPE CDATA #IMPLIED >
<!ELEMENT PROCEDURE ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | TAG )* >
-->

<!ELEMENT PROCEDURE ( ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | TAG | RETURN | THROWS )* , SUMMARY? ) >
<!ATTLIST PROCEDURE NAME CDATA #REQUIRED >
<!ATTLIST PROCEDURE ACTION CDATA #IMPLIED >
<!ATTLIST PROCEDURE VERSION CDATA #IMPLIED >
<!ATTLIST PROCEDURE INHERITANCE CDATA #IMPLIED >
<!ATTLIST PROCEDURE ORDERING CDATA #IMPLIED >
<!ATTLIST PROCEDURE SCOPE CDATA #IMPLIED >

<!ELEMENT RETURN ( COMMENT? ) >
<!ATTLIST RETURN TYPE CDATA #REQUIRED >
<!ATTLIST RETURN NAME CDATA #IMPLIED >
<!ATTLIST RETURN COLLECTIONTYPE CDATA #IMPLIED >
<!ATTLIST RETURN SUPERTYPE CDATA #IMPLIED >




<!ELEMENT THROWS ( COMMENT? ) >
<!ATTLIST THROWS NAME CDATA #REQUIRED >

<!ELEMENT FIELD ( COMMENT? ) >
<!ATTLIST FIELD NAME CDATA #REQUIRED >
<!ATTLIST FIELD TYPE CDATA #REQUIRED >
<!ATTLIST FIELD DEFAULT CDATA #IMPLIED >

<!ELEMENT TYPE ( COMMENT | COMMENT_FIRST_LINE | FIELD | RETURN | TAG )* >
<!ATTLIST TYPE NAME CDATA #REQUIRED >

<!ELEMENT VARIABLE ( COMMENT | COMMENT_FIRST_LINE | RETURN  )* >
<!--  VARIABLE NAME may not be unique in Application.xml -->
<!ATTLIST VARIABLE NAME CDATA #REQUIRED >
<!ATTLIST VARIABLE ACTION CDATA #IMPLIED >
<!ATTLIST VARIABLE DEFAULT CDATA #IMPLIED >
<!ATTLIST VARIABLE VERSION CDATA #IMPLIED >

<!ELEMENT TABLE ( COMMENT | COLUMN | TAG )* >
<!ATTLIST TABLE NAME CDATA #REQUIRED >
<!ATTLIST TABLE SCHEMA CDATA #IMPLIED >

<!ELEMENT COLUMN ( COMMENT? ) >
<!ATTLIST COLUMN CONSTRAINT CDATA #IMPLIED >
<!ATTLIST COLUMN NAME CDATA #REQUIRED >
<!ATTLIST COLUMN TYPE CDATA #REQUIRED >

<!ELEMENT GENERATOR ( OBJECTS, CREATED, SETTINGS , SUMMARY? ) >

<!ELEMENT OBJECTS ( PROCESSED, SKIPPED ) >

<!ELEMENT PROCESSED EMPTY >
<!ATTLIST PROCESSED COUNT CDATA #REQUIRED >

<!ELEMENT SKIPPED ( OBJECT* ) >
<!ATTLIST SKIPPED COUNT CDATA #REQUIRED >

<!ELEMENT OBJECT EMPTY >
<!ATTLIST OBJECT NAME CDATA #REQUIRED >
<!ATTLIST OBJECT ERROR CDATA #REQUIRED >

<!ELEMENT CREATED EMPTY >
<!ATTLIST CREATED DATE CDATA #REQUIRED >
<!ATTLIST CREATED TIME CDATA #REQUIRED >

<!ELEMENT SETTINGS EMPTY >
<!ATTLIST SETTINGS VERBOSE CDATA #IMPLIED >
<!ATTLIST SETTINGS SHOW_SKIPPED_PACKAGES CDATA #IMPLIED >
<!ATTLIST SETTINGS IGNORE_INFORMAL_COMMENTS CDATA #IMPLIED >
<!ATTLIST SETTINGS INPUT_ENCODING CDATA #IMPLIED >
<!ATTLIST SETTINGS DEFAULT_NAMES_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS DEFAULT_KEYWORDS_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS NAMES_TO_DEFAULT_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS NAMES_TO_UPPER_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS NAMES_TO_LOWER_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS KEYWORDS_TO_DEFAULT_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS KEYWORDS_TO_UPPER_CASE CDATA #IMPLIED >
<!ATTLIST SETTINGS KEYWORDS_TO_LOWER_CASE CDATA #IMPLIED >

<!ELEMENT TRIGGER ( ( COMMENT | COMMENT_FIRST_LINE | DECLARATION | TAG | CONSTANT | FUNCTION | PROCEDURE | TYPE | VARIABLE | TIMINGPOINTSECTION )* , SUMMARY?  )>
<!ATTLIST TRIGGER NAME CDATA #REQUIRED >
<!ATTLIST TRIGGER SCHEMA CDATA #IMPLIED >
<!ATTLIST TRIGGER TYPE CDATA #IMPLIED >

<!ELEMENT DECLARATION EMPTY >
<!ATTLIST DECLARATION TEXT CDATA #REQUIRED >

<!ELEMENT TIMINGPOINTSECTION ( COMMENT | COMMENT_FIRST_LINE | TAG )* >
<!ATTLIST TIMINGPOINTSECTION NAME CDATA #REQUIRED >
<!ATTLIST TIMINGPOINTSECTION TYPE CDATA #REQUIRED >

<!-- Element containing summary from parser-->
<!ELEMENT SUMMARY EMPTY >
<!ATTLIST SETTINGS START_LINE CDATA #IMPLIED >
<!ATTLIST SETTINGS START_COLUMN CDATA #IMPLIED >
<!ATTLIST SETTINGS END_LINE CDATA #IMPLIED >
<!ATTLIST SETTINGS END_COLUMN CDATA #IMPLIED >
<!ATTLIST SETTINGS LINES CDATA #IMPLIED >
<!ATTLIST SETTINGS LINES_OF_CODE CDATA #IMPLIED >
<!ATTLIST SETTINGS LINES_OF_COMMENTS CDATA #IMPLIED >
<!ATTLIST SETTINGS COMPLEXITY CDATA #IMPLIED >

=== jpromocion/plsql-j-utilxml/pldoc/application.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE APPLICATION SYSTEM "application.dtd">
<APPLICATION NAME="plsql-j-utilxml">
  <PACKAGE_BODY NAME="UTILXML" SCHEMA="">
    <FUNCTION NAME="GETNAMESPACESTRING">
      <COMMENT_FIRST_LINE><![CDATA[ Return literal string of namespace
]]></COMMENT_FIRST_LINE>
      <COMMENT><![CDATA[ Return literal string of namespace
]]></COMMENT>
      <ARGUMENT MODE="IN" NAME="TNAMESPACES" TYPE="T_NAMESPACES">
        <COMMENT><![CDATA[Table with all necessary namespace.]]></COMMENT>
      </ARGUMENT>
      <RETURN TYPE="VARCHAR2">
        <COMMENT><![CDATA[Literal namespace string]]></COMMENT>
      </RETURN>
      <TAG TYPE="@PARAM">
        <COMMENT><![CDATA[tNameSpaces Table with all necessary namespace.]]></COMMENT>
      </TAG>
      <TAG TYPE="@RETURN">
        <COMMENT><![CDATA[Literal namespace string]]></COMMENT>
      </TAG>
      <SUMMARY END_COLUMN="25" END_LINE="27" LINES="14" START_COLUMN="12" START_LINE="14"/>
    </FUNCTION>
    <PROCEDURE NAME="ADDNAMESPACEXMLTABLE">
      <COMMENT_FIRST_LINE><![CDATA[ For a XMLTABLE select, add namespace information
]]></COMMENT_FIRST_LINE>
      <COMMENT><![CDATA[ For a XMLTABLE select, add namespace information
]]></COMMENT>
      <ARGUMENT MODE="IN OUT" NAME="SQLSELECT" TYPE="VARCHAR2">
        <COMMENT><![CDATA[Buildinf select. It will be completed]]></COMMENT>
      </ARGUMENT>
      <ARGUMENT MODE="IN" NAME="TNAMESPACES" TYPE="T_NAMESPACES"/>
      <TAG TYPE="@PARAM">
        <COMMENT><![CDATA[sqlSelect Buildinf select. It will be completed]]></COMMENT>
      </TAG>
      <TAG TYPE="@PARAM">
        <COMMENT><![CDATA[Table with all necessary namespace. If not namespace -> NULL.]]></COMMENT>
      </TAG>
      <SUMMARY END_COLUMN="27" END_LINE="52" LINES="19" START_COLUMN="13" START_LINE="34"/>
    </PROCEDURE>
    <FUNCTION NAME="ESCAPEDSTRINGXML">
      <COMMENT_FIRST_LINE><![CDATA[******************************************************************************
******************** GENERAL USE *********************************
******************************************************************************
]]></COMMENT_FIRST_LINE>
      <COMMENT><![CDATA[******************************************************************************
******************** GENERAL USE *********************************
******************************************************************************
]]></COMMENT>
      <ARGUMENT MODE="IN" NAME="STRING" TYPE="VARCHAR2"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="23" END_LINE="64" LINES="5" START_COLUMN="12" START_LINE="60"/>
    </FUNCTION>
    <FUNCTION NAME="ESCAPEDSTRINGXML">
      <ARGUMENT MODE="IN" NAME="STRING" TYPE="CLOB"/>
      <RETURN TYPE="CLOB"/>
      <SUMMARY END_COLUMN="23" END_LINE="70" LINES="5" START_COLUMN="12" START_LINE="66"/>
    </FUNCTION>
    <FUNCTION NAME="UNESCAPEDSTRINGXML">
      <ARGUMENT MODE="IN" NAME="STRING" TYPE="VARCHAR2"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="25" END_LINE="76" LINES="5" START_COLUMN="12" START_LINE="72"/>
    </FUNCTION>
    <FUNCTION NAME="UNESCAPEDSTRINGXML">
      <ARGUMENT MODE="IN" NAME="STRING" TYPE="CLOB"/>
      <RETURN TYPE="CLOB"/>
      <SUMMARY END_COLUMN="25" END_LINE="82" LINES="5" START_COLUMN="12" START_LINE="78"/>
    </FUNCTION>
    <FUNCTION NAME="NEWDOMDOCUMENT">
      <COMMENT_FIRST_LINE><![CDATA[ Create new DOMDocument without root node
]]></COMMENT_FIRST_LINE>
      <COMMENT><![CDATA[ Create new DOMDocument without root node
]]></COMMENT>
      <RETURN TYPE="DBMS_XMLDOM.DOMDOCUMENT">
        <COMMENT><![CDATA[new DOMDocument xml]]></COMMENT>
      </RETURN>
      <TAG TYPE="@RETURN">
        <COMMENT><![CDATA[new DOMDocument xml]]></COMMENT>
      </TAG>
      <SUMMARY END_COLUMN="22" END_LINE="104" LINES="11" START_COLUMN="13" START_LINE="94"/>
    </FUNCTION>
    <FUNCTION NAME="STRINGTODOMDOCUMENT">
      <ARGUMENT MODE="IN" NAME="XML" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <SUMMARY END_COLUMN="26" END_LINE="117" LINES="11" START_COLUMN="12" START_LINE="107"/>
    </FUNCTION>
    <FUNCTION NAME="STRINGTODOMDOCUMENT">
      <ARGUMENT MODE="IN" NAME="XML" TYPE="CLOB"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <SUMMARY END_COLUMN="26" END_LINE="129" LINES="11" START_COLUMN="12" START_LINE="119"/>
    </FUNCTION>
    <FUNCTION NAME="CREATENODE">
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <ARGUMENT MODE="IN" NAME="DADNODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="NAMENODE" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODE"/>
      <SUMMARY END_COLUMN="17" END_LINE="146" LINES="16" START_COLUMN="12" START_LINE="131"/>
    </FUNCTION>
    <FUNCTION NAME="CREATETEXTNODE">
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <ARGUMENT MODE="IN" NAME="DADNODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="NAMENODE" TYPE="VARCHAR2"/>
      <ARGUMENT MODE="IN" NAME="TEXT" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODE"/>
      <SUMMARY END_COLUMN="21" END_LINE="168" LINES="21" START_COLUMN="12" START_LINE="148"/>
    </FUNCTION>
    <PROCEDURE NAME="CREATEATTRIBUTE">
      <ARGUMENT MODE="IN" NAME="NODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="NAME" TYPE="VARCHAR2"/>
      <ARGUMENT MODE="IN" NAME="VALUE" TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="22" END_LINE="177" LINES="8" START_COLUMN="13" START_LINE="170"/>
    </PROCEDURE>
    <FUNCTION NAME="ADDNODEXMLTYPE">
      <ARGUMENT MODE="IN" NAME="XML" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <ARGUMENT MODE="IN" NAME="DADNODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="XMLNODE" TYPE="XMLTYPE"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODE"/>
      <SUMMARY END_COLUMN="21" END_LINE="201" LINES="23" START_COLUMN="12" START_LINE="179"/>
    </FUNCTION>
    <FUNCTION NAME="GETROOT">
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMELEMENT"/>
      <SUMMARY END_COLUMN="14" END_LINE="210" LINES="8" START_COLUMN="12" START_LINE="203"/>
    </FUNCTION>
    <FUNCTION NAME="GETNODELIST">
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <ARGUMENT MODE="IN" NAME="NAMENODE" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODELIST"/>
      <SUMMARY END_COLUMN="18" END_LINE="228" LINES="17" START_COLUMN="12" START_LINE="212"/>
    </FUNCTION>
    <FUNCTION NAME="GETNODELIST">
      <ARGUMENT MODE="IN" NAME="DADNODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODELIST"/>
      <SUMMARY END_COLUMN="18" END_LINE="242" LINES="13" START_COLUMN="12" START_LINE="230"/>
    </FUNCTION>
    <FUNCTION NAME="GETNODE">
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <ARGUMENT MODE="IN" NAME="NAMENODE" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODE"/>
      <SUMMARY END_COLUMN="14" END_LINE="256" LINES="13" START_COLUMN="12" START_LINE="244"/>
    </FUNCTION>
    <FUNCTION NAME="GETNODE">
      <ARGUMENT MODE="IN" NAME="DADNODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="NAMENODE" TYPE="VARCHAR2"/>
      <RETURN TYPE="DBMS_XMLDOM.DOMNODE"/>
      <SUMMARY END_COLUMN="14" END_LINE="277" LINES="20" START_COLUMN="12" START_LINE="258"/>
    </FUNCTION>
    <FUNCTION NAME="GETATTRIBUTE">
      <ARGUMENT MODE="IN" NAME="DOMELEMENT" TYPE="DBMS_XMLDOM.DOMELEMENT"/>
      <ARGUMENT MODE="IN" NAME="NAMEATT" TYPE="VARCHAR2"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="19" END_LINE="284" LINES="6" START_COLUMN="12" START_LINE="279"/>
    </FUNCTION>
    <FUNCTION NAME="GETATTRIBUTE">
      <ARGUMENT MODE="IN" NAME="NODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <ARGUMENT MODE="IN" NAME="NAMEATT" TYPE="VARCHAR2"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="19" END_LINE="303" LINES="18" START_COLUMN="12" START_LINE="286"/>
    </FUNCTION>
    <FUNCTION NAME="GETNAME">
      <ARGUMENT MODE="IN" NAME="NODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="14" END_LINE="312" LINES="8" START_COLUMN="12" START_LINE="305"/>
    </FUNCTION>
    <FUNCTION NAME="GETVALUE">
      <ARGUMENT MODE="IN" NAME="NODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <RETURN TYPE="VARCHAR2"/>
      <SUMMARY END_COLUMN="15" END_LINE="326" LINES="13" START_COLUMN="12" START_LINE="314"/>
    </FUNCTION>
    <FUNCTION NAME="GETVALUECDATA">
      <ARGUMENT MODE="IN" NAME="NODE" TYPE="DBMS_XMLDOM.DOMNODE"/>
      <RETURN TYPE="CLOB"/>
      <SUMMARY END_COLUMN="20" END_LINE="365" LINES="38" START_COLUMN="12" START_LINE="328"/>
    </FUNCTION>
    <FUNCTION NAME="DOMDOCUMENTTOXMLTYPE">
      <COMMENT_FIRST_LINE><![CDATA[******************************************************************************
******************** USE XMLTYPE *******************************************
******************************************************************************
]]></COMMENT_FIRST_LINE>
      <COMMENT><![CDATA[******************************************************************************
******************** USE XMLTYPE *******************************************
******************************************************************************
]]></COMMENT>
      <ARGUMENT MODE="IN" NAME="DOCUMENT" TYPE="DBMS_XMLDOM.DOMDOCUMENT"/>
      <RETURN TYPE="XMLTYPE"/>
      <SUMMARY END_COLUMN="27" END_LINE="385" LINES="11" START_COLUMN="12" START_LINE="375"/>
    </FUNCTION>
    <FUNCTION NAME="XMLTYPETOCLOB">
      <ARGUMENT MODE="IN" NAME="XML" TYPE="XMLTYPE"/>
      <RETURN TYPE="CLOB"/>
      <SUMMARY END_COLUMN="20" END_LINE="391" LINES="5" START_COLUMN="12" START_LINE="387"/>
    </FUNCTION>
    <FUNCTION NAME="CLOBTOXMLTYPE">
      <ARGUMENT MODE="IN" NAME="XML" TYPE="CLOB"/>
      <RETURN TYPE="XMLTYPE"/>
